import "./../styles/globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/toaster";

/* Custom Components */
import { ThemeProvider } from "@/context/theme-provider";
import { BreadcrumbComponent } from "@/utils/breadcrumb";
import AppHeader, { NavBar } from "@/components/shared/app-header";
import { ToggleTheme } from "@/components/shared/toggle-theme";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Pro-Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        {/* <UserProvider> */}
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky justify-between top-0 flex bg-white dark:bg-black shrink-0 items-center border-b p-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
            <div className="flex items-center gap-1 text-left text-sm leading-tight">
              <NavBar />
              <Separator orientation="vertical" className="mr-2 ml-2 h-4" />
              {/* <BreadcrumbComponent /> */}
            </div>
            <div className="flex items-center gap-7">
              {/* <AuthButtons /> */}
              <ToggleTheme />
            </div>
          </header>
          <main>{children}</main>
          <footer className="text-sm text-gray-400 right-20 absolute mb-5 bottom-0 h-[2.5rem]">
            <span>
              Patchelli Carmel Fred &copy; 2025 ASD - All Rights Reserved
            </span>
          </footer>
        </ThemeProvider>
        {/* </UserProvider> */}
        <Toaster key={"toaster"} />
      </body>
    </html>
  );
}
